name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Output dummy aws-exports.js
        uses: ./.github/workflows/output-dummy-aws-exports.yaml
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
