name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened]
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Export dummy aws-exports.js
  #       uses: ./.github/actions/export
  #     - name: Install modules
  #       run: npm ci
  test:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export dummy aws-exports.js
        uses: ./.github/actions/export
      - name: Install modules
        run: npm ci
      - name: Run format with Prettier
        run: npm run fmt
      - name: Run lint
        run: npm run lint
      - name: Run tests ⚗️
        run: npm run test
        env:
          TZ: 'Asia/Tokyo'
  e2e:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - name: Run Component tests with Cypress 🧪
        uses: cypress-io/github-action@v2
        with:
          # we have already installed everything
          install: false
          # to run component tests we need to use "cypress run-ct"
          command: npm run cy:run:ct
  notification:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - name: Slack notification success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: 'Tests success :rocket:'
          SLACK_COLOR: '#5cb85c'
      - name: Slack notification failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: 'Tests failure :boom:'
          SLACK_COLOR: '#dc143c'
