name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export dummy aws-exports.js
        uses: ./.github/actions/export
      - name: Install modules
        run: npm ci
      - name: Set timezone of JST
        env:
          TZ: 'Asia/Tokyo'
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
      - name: Run tests
        run: npm run test
