name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export dummy aws-exports.js
        uses: ./.github/actions/export
      - name: Install modules
        run: npm ci
      - name: Run format with Prettier
        run: npm run fmt
      - name: Run lint
        run: npm run lint
      - name: Run tests ⚗️
        run: npm run test
        env:
          TZ: 'Asia/Tokyo'
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - name: Run Component tests with Cypress 🧪
        uses: cypress-io/github-action@v2
        with:
          # we have already installed everything
          install: false
          # to run component tests we need to use "cypress run-ct"
          command: npm run cy:run:ct
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
