name: Tests
on: push
jobs:
  test-job:
    # runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Checkout
        uses: ./.github/workflows/checkout.yaml
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
