name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # build
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export dummy build.gradle
        uses: ./.github/actions/gradle
      - name: Java Install
        # run: sudo yum install -y java-11-amazon-corretto-headless
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'gradle'
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli
      - name: Install modules
        run: npm ci
      - name: Export dummy aws-exports.js
        uses: ./.github/actions/export
      # Jest test
      - name: Run format with Prettier
        run: npm run fmt
      - name: Run lint
        run: npm run lint
      - name: Run tests ⚗️
        run: npm run test
        env:
          TZ: 'Asia/Tokyo'
      # Run Amplify mock
      - name: Amplify pull
        run: amplify pull --appId ${{ secrets.AMPLIFY_APP_ID }} --envName develop -y
      - name: Amplify mocking
        run: npm run mock
      # Cypress e2e
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      # Cypress component testing
      - name: Run Component tests with Cypress 🧪
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run cy:run:ct
      # notification
      - name: Slack notification success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: 'Tests success :rocket:'
          SLACK_COLOR: '#5cb85c'
      - name: Slack notification failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: 'Tests failure :boom:'
          SLACK_COLOR: '#dc143c'
